[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"
watchPatterns = ["api/**"]

[general]
rootDir = "api"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
