const path = require('path')
const fs = require('fs')

module.exports = async (fastify) => {
  const { supabase } = fastify

  // GET /agent/status - Check if any agent is online
  fastify.get('/status', { preHandler: fastify.authenticate }, async (req, reply) => {
    const userId = req.user.id

    const [{ data: agents }, { data: profile }] = await Promise.all([
      supabase
        .from('agent_heartbeats')
        .select('agent_id, last_seen, hostname, platform, user_id')
        .gte('last_seen', new Date(Date.now() - 15000).toISOString())
        .or(`user_id.is.null,user_id.eq.${userId}`)
        .order('last_seen', { ascending: false }),
      supabase
        .from('profiles')
        .select('preferred_executor_id')
        .eq('id', userId)
        .single(),
    ])

    return {
      online: (agents?.length || 0) > 0,
      agents: agents || [],
      preferredExecutorId: profile?.preferred_executor_id || null,
    }
  })

  // PUT /agent/executor - Set preferred executor for current user
  fastify.put('/executor', { preHandler: fastify.authenticate }, async (req, reply) => {
    const userId = req.user.id
    const { executorId } = req.body // null = auto (any)

    await supabase
      .from('profiles')
      .update({ preferred_executor_id: executorId || null })
      .eq('id', userId)

    return { ok: true, preferredExecutorId: executorId || null }
  })

  // GET /agent/download - Download agent as ZIP (any authenticated user)
  fastify.get('/download', { preHandler: fastify.authenticate }, async (req, reply) => {

    const archiver = require('archiver')

    // Agent source dir — check multiple possible locations
    const possibleDirs = [
      process.env.AGENT_DIR,
      path.resolve(__dirname, '../../../../socialflow-agent'),  // local dev
      path.resolve(__dirname, '../../../socialflow-agent'),      // local dev alt
      '/app/socialflow-agent',                                   // Railway deployment
    ].filter(Boolean)
    const agentDir = possibleDirs.find(d => fs.existsSync(d))
    if (!agentDir) {
      return reply.code(404).send({ error: 'Agent directory not found. Set AGENT_DIR env variable.' })
    }

    const excludeNames = ['node_modules', 'debug', 'dist', 'electron', '.env', 'config.env', 'nul', '.git', 'package-lock.json', '.env.example', 'create-icon.js', 'scripts']

    const archive = archiver('zip', { zlib: { level: 6 } })
    archive.on('error', (err) => {
      console.error('[AGENT-DOWNLOAD] Archive error:', err)
    })

    // Add files recursively, excluding unwanted
    const entries = fs.readdirSync(agentDir)
    const included = []
    for (const entry of entries) {
      if (excludeNames.includes(entry)) continue
      const fullPath = path.join(agentDir, entry)
      const stat = fs.statSync(fullPath)
      if (stat.isDirectory()) {
        archive.directory(fullPath, `socialflow-agent/${entry}`)
        included.push(`${entry}/`)
      } else {
        archive.file(fullPath, { name: `socialflow-agent/${entry}` })
        included.push(entry)
      }
    }
    console.log(`[AGENT-DOWNLOAD] Dir: ${agentDir}, Files: ${included.join(', ')}`)

    // Inject credentials - both .env AND lib/config.js for reliability
    // (some Windows extractors skip dotfiles like .env)
    const os = require('os')
    const agentId = `agent-${os.hostname()}-${Date.now().toString(36)}`
    const supabaseUrl = process.env.SUPABASE_URL || ''
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
    const anonKey = process.env.SUPABASE_ANON_KEY || ''
    const frontendUrl = process.env.FRONTEND_URL || 'https://socialflow-bice.vercel.app'

    const envContent = `# Auto-generated by SocialFlow
SUPABASE_URL=${supabaseUrl}
SUPABASE_SERVICE_ROLE_KEY=${serviceKey}
SUPABASE_ANON_KEY=${anonKey}
FRONTEND_URL=${frontendUrl}
AGENT_ID=${agentId}
`
    archive.append(envContent, { name: 'socialflow-agent/config.env' })

    // Also inject lib/config.js as fallback (always works on Windows)
    const configContent = `// Auto-generated by SocialFlow - DO NOT EDIT
module.exports = {
  SUPABASE_URL: '${supabaseUrl}',
  SUPABASE_SERVICE_ROLE_KEY: '${serviceKey}',
  SUPABASE_ANON_KEY: '${anonKey}',
  FRONTEND_URL: '${frontendUrl}',
  AGENT_ID: '${agentId}',
}
`
    archive.append(configContent, { name: 'socialflow-agent/lib/config.js' })

    archive.finalize()

    return reply
      .header('Content-Type', 'application/zip')
      .header('Content-Disposition', 'attachment; filename="socialflow-agent.zip"')
      .send(archive)
  })
}
