const path = require('path')
const fs = require('fs')

module.exports = async (fastify) => {
  const { supabase } = fastify

  // GET /agent/status - Check if any agent is online
  fastify.get('/status', { preHandler: fastify.authenticate }, async (req, reply) => {
    const { data: agents } = await supabase
      .from('agent_heartbeats')
      .select('agent_id, last_seen, hostname')
      .gte('last_seen', new Date(Date.now() - 15000).toISOString())
      .order('last_seen', { ascending: false })

    return {
      online: (agents?.length || 0) > 0,
      agents: agents || [],
    }
  })

  // GET /agent/download - Download agent as ZIP (any authenticated user)
  fastify.get('/download', { preHandler: fastify.authenticate }, async (req, reply) => {

    const archiver = require('archiver')

    // Agent source dir — check multiple possible locations
    const possibleDirs = [
      process.env.AGENT_DIR,
      path.resolve(__dirname, '../../../../socialflow-agent'),  // local dev
      path.resolve(__dirname, '../../../socialflow-agent'),      // local dev alt
      '/app/socialflow-agent',                                   // Railway deployment
    ].filter(Boolean)
    const agentDir = possibleDirs.find(d => fs.existsSync(d))
    if (!agentDir) {
      return reply.code(404).send({ error: 'Agent directory not found. Set AGENT_DIR env variable.' })
    }

    const excludeNames = ['node_modules', 'debug', 'dist', 'electron', '.env', 'nul', '.git', 'package-lock.json', '.env.example', 'create-icon.js']

    const archive = archiver('zip', { zlib: { level: 6 } })
    archive.on('error', (err) => {
      console.error('[AGENT-DOWNLOAD] Archive error:', err)
    })

    // Add files recursively, excluding unwanted
    const entries = fs.readdirSync(agentDir)
    for (const entry of entries) {
      if (excludeNames.includes(entry)) continue
      const fullPath = path.join(agentDir, entry)
      const stat = fs.statSync(fullPath)
      if (stat.isDirectory()) {
        archive.directory(fullPath, `socialflow-agent/${entry}`)
      } else {
        archive.file(fullPath, { name: `socialflow-agent/${entry}` })
      }
    }

    // Inject .env with pre-configured credentials (admin already set these)
    const os = require('os')
    const agentId = `agent-${os.hostname()}-${Date.now().toString(36)}`
    const envContent = `# Auto-generated by SocialFlow
SUPABASE_URL=${process.env.SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${process.env.SUPABASE_SERVICE_ROLE_KEY || ''}
SUPABASE_ANON_KEY=${process.env.SUPABASE_ANON_KEY}

# Frontend
FRONTEND_URL=${process.env.FRONTEND_URL || 'https://socialflow-bice.vercel.app'}

# Agent
AGENT_ID=${agentId}
`
    archive.append(envContent, { name: 'socialflow-agent/.env' })

    archive.finalize()

    return reply
      .header('Content-Type', 'application/zip')
      .header('Content-Disposition', 'attachment; filename="socialflow-agent.zip"')
      .send(archive)
  })
}
