#!/usr/bin/env node
/**
 * Build SocialFlow Agent exe
 * Reads .env → injects config into build → creates exe
 *
 * Usage: node scripts/build.js
 */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env')
const CONFIG_PATH = path.join(ROOT, 'lib', 'config.js')

console.log('=== SocialFlow Agent Builder ===\n')

// 1. Read .env
if (!fs.existsSync(ENV_PATH)) {
  console.error('[ERROR] .env file not found! Create .env with Supabase credentials first.')
  process.exit(1)
}

const envContent = fs.readFileSync(ENV_PATH, 'utf8')
const envVars = {}
for (const line of envContent.split('\n')) {
  const match = line.match(/^\s*([^#=]+?)\s*=\s*(.*)$/)
  if (match) envVars[match[1].trim()] = match[2].trim()
}

// Validate required vars
const required = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY']
for (const key of required) {
  if (!envVars[key]) {
    console.error(`[ERROR] Missing required env var: ${key}`)
    process.exit(1)
  }
}

console.log('[OK] .env loaded')
console.log(`  SUPABASE_URL: ${envVars.SUPABASE_URL}`)
console.log(`  AGENT_ID: ${envVars.AGENT_ID || '(auto-generated)'}`)

// 2. Generate config.js with embedded credentials
// No user_id embedded — SaaS login picks user at runtime, stores in
// userData/auth.json. Single binary, many users, no per-user rebuild.
const configContent = `// Auto-generated by build script — DO NOT EDIT
// These credentials are embedded at build time
module.exports = {
  SUPABASE_URL: ${JSON.stringify(envVars.SUPABASE_URL || '')},
  SUPABASE_SERVICE_ROLE_KEY: ${JSON.stringify(envVars.SUPABASE_SERVICE_ROLE_KEY || '')},
  SUPABASE_ANON_KEY: ${JSON.stringify(envVars.SUPABASE_ANON_KEY || '')},
  FRONTEND_URL: ${JSON.stringify(envVars.FRONTEND_URL || 'https://socialflow888.vercel.app')},
  AGENT_ID: ${JSON.stringify(envVars.AGENT_ID || '')},
  API_URL: ${JSON.stringify(envVars.API_URL || 'https://103-142-24-60.sslip.io')},
  AGENT_SECRET_KEY: ${JSON.stringify(envVars.AGENT_SECRET_KEY || '')},
}
`
fs.writeFileSync(CONFIG_PATH, configContent)
console.log('[OK] lib/config.js generated with embedded credentials')

// 3. Build with electron-packager
console.log('\n[BUILD] Creating exe...')
try {
  const cmd = [
    'npx', '@electron/packager', '.',
    '"SocialFlow Agent"',
    '--platform=win32',
    '--arch=x64',
    '--out=dist',
    '--overwrite',
    // Anchor each pattern with ^/... so 'dist' / 'scripts' don't match
    // node_modules/<pkg>/dist or node_modules/<pkg>/scripts and nuke
    // dependency files. Hit us with the axios 1.13 dist folder going
    // missing → "Cannot find module axios.cjs".
    '--ignore="(^/dist$|^/dist/|^/debug$|^/debug/|^/\\.env$|^/nul$|^/\\.git|^/package-lock\\.json$|^/scripts$|^/scripts/)"',
    '--icon=electron/icon.ico',
    // asar=false so agent.js + node_modules stay unpacked. fork() and
    // spawn() can't read files inside app.asar; this keeps the fork
    // path (Playwright install + agent.js) working.
    '--asar=false',
  ].join(' ')

  execSync(cmd, { cwd: ROOT, stdio: 'inherit', shell: true })
  console.log('\n[OK] Build complete!')

  // Rename packager's default "SocialFlow Agent-win32-x64" folder to
  // "win-unpacked" so the output path is stable across rebuilds.
  // Otherwise old builds pile up and existing shortcuts point to stale
  // binaries. Delete any prior win-unpacked first to avoid mv conflicts.
  const packagerOut = path.join(ROOT, 'dist', 'SocialFlow Agent-win32-x64')
  const stableOut = path.join(ROOT, 'dist', 'win-unpacked')
  if (fs.existsSync(packagerOut)) {
    if (fs.existsSync(stableOut)) {
      fs.rmSync(stableOut, { recursive: true, force: true })
    }
    fs.renameSync(packagerOut, stableOut)
    console.log('[OK] Renamed → dist/win-unpacked (stable path)')
  }
} catch (err) {
  console.error('\n[ERROR] Build failed:', err.message)
  // Clean up config.js to not leave secrets in source
  fs.unlinkSync(CONFIG_PATH)
  process.exit(1)
}

// 4. Clean up — remove config.js from source (it's inside the exe now)
fs.unlinkSync(CONFIG_PATH)
console.log('[OK] Cleaned up lib/config.js from source')

// 5. Show result
const distDir = path.join(ROOT, 'dist', 'win-unpacked')
if (fs.existsSync(distDir)) {
  const exePath = path.join(distDir, 'SocialFlow Agent.exe')
  if (fs.existsSync(exePath)) {
    const size = (fs.statSync(exePath).size / 1024 / 1024).toFixed(1)
    console.log(`\n=== Build Output ===`)
    console.log(`  Folder: ${distDir}`)
    console.log(`  EXE: SocialFlow Agent.exe (${size} MB)`)
    console.log(`  Credentials: embedded (no .env needed)`)
    console.log(`\nUser just double-clicks the exe and it works!`)
  }
}
